root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/owncast ."
  bin = "./tmp/owncast"
  full_bin = "./tmp/owncast -database ./data/owncast.db"
  include_ext = ["go"]
  exclude_dir = ["tmp", "web", "static/web", "node_modules", "data"]
  exclude_regex = ["_test\\.go$"]
  delay = 1000
  kill_delay = 500
  send_interrupt = true
  stop_on_error = true

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
